version: "3"

services:
  web:
    build: .
    ports:
      - "80:80"

  # lb:
  #   image: dockercloud/haproxy
  #   links:
  #    - web
  #   ports:
  #    - '3020:80'
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
