version: "3"

services:
  web:
    build: .
    ports:
      - "3000-3010:3000"

  lb:
    image: dockercloud/haproxy
    links:
     - web
    ports:
     - '3020:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
